apiVersion: builtin
kind: LabelTransformer
metadata:
  name: stub
labels:
  mesh: $CLUSTER_NAME
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/selector/matchLabels
  create: true
  kind: Deployment
- path: spec/template/metadata/labels
  create: true
  kind: Deployment