apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: north-south-gw-cert
  namespace: istio-ingress
spec:
  secretName: north-south-gw-tls
  issuerRef:
    name: ingress-tls-issuer
    kind: Issuer
  commonName: ${PUBLIC_INSTRUQT_SANDBOX_ENDPOINT}
  dnsNames:
    - ${PUBLIC_INSTRUQT_SANDBOX_ENDPOINT}