apiVersion: security.policy.gloo.solo.io/v2
kind: AccessPolicy
metadata:
  name: in-namespace-access
  namespace: web-team
spec:
  applyToDestinations:
    - selector:
        workspace: web-team
  config:
    authz:
      allowedClients:
        - serviceAccountSelector:
            namespace: web-ui
---
apiVersion: security.policy.gloo.solo.io/v2
kind: AccessPolicy
metadata:
  name: gateway-access
  namespace: web-team
spec:
  applyToDestinations:
    - selector:
        workspace: web-team
  config:
    authz:
      allowedClients:
        - serviceAccountSelector:
            workspace: ops-team
            labels:
              istio: ingressgateway