apiVersion: security.policy.gloo.solo.io/v2
kind: AccessPolicy
metadata:
  name: deny-all
  namespace: backend-apis-team
spec:
  applyToWorkloads:
    - {}
  config:
    authn:
      tlsMode: STRICT
    authz: {}
