# Name allows overriding the release name. Generally this should not be set
name: ""

# Revision declares which revision this gateway is a part of
revision: "${ISTIO_REVISION}"

imagePullSecrets: []

replicaCount: 1

kind: Deployment

rbac:
  # If enabled, roles will be created to enable accessing certificates from Gateways. This is not needed
  # when using http://gateway-api.org/.
  enabled: true

serviceAccount:
  # If set, a service account will be created. Otherwise, the default is used
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set, the release name is used
  name: ""

podAnnotations:
  prometheus.io/port: "15020"
  prometheus.io/scrape: "true"
  prometheus.io/path: "/stats/prometheus"
  inject.istio.io/templates: "gateway"
  sidecar.istio.io/inject: "true"

# Define the security context for the pod.
# If unset, this will be automatically set to the minimum privileges required to bind to port 80 and 443.
# On Kubernetes 1.22+, this only requires the `net.ipv4.ip_unprivileged_port_start` sysctl.
securityContext: ~
containerSecurityContext: ~

service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  annotations: {}
  ports:
    # Health check port. For AWS ELBs, this port must be listed first.
    # Disabled to stop conflicting on instruqt
    # - name: status-port
    #   port: 15021
    #   protocol: TCP
    #   targetPort: 15021
    # Port for multicluster mTLS passthrough
    # Dont change the name since Gloo Mesh looks for "tls"
    - name: tls
      port: 15443
      targetPort: 15443
    # Required for VM onboarding discovery address
    - name: tcp-istiod
      port: 15012
      targetPort: 15012
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""
  externalIPs: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Pod environment variables
env:
  # Required by Gloo Mesh for east/west routing
  # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
  ISTIO_META_ROUTER_MODE: "sni-dnat"

# Labels to apply to all resources
labels: {}

# Annotations to apply to all resources
annotations: {}

nodeSelector: {}

tolerations: []

topologySpreadConstraints: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - istio-eastwestgateway
          topologyKey: kubernetes.io/hostname
        weight: 100

# If specified, the gateway will act as a network gateway for the given network.
networkGateway: ""